# Welcome to Jekyll!

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Hurling at Stanford
email: hurling.stanford@gmail.com
description: #>- # this means to ignore newlines until next item
  #Follow/subscribe to our accounts to hear the latest and spread the 
  #frenetic grace of hurling with your friends!
domain: "darachm.github.io"
baseurl: "/stanford-hurling" # for deploy
#baseurl: "" # for testing locally
url: "https://darachm.github.io/stanford-hurling" # the base hostname & protocol for your site, e.g. http://example.com
author: ''

minima:
    skin: 'solarized'
    social_links:
        twitter: 'stanfordhurling'
        facebook: 'groups/stanfordhurling'
        facebook2: 'South-Bay-Gaelic-Sports-100337136093794'
        #instagram: 'stanfordhurling'
    date_format: "%Y-%m-%d"

header_pages:
  - hurling-info.md
  - info.md
  - club.md
  - calendar.md

# Build settings
#remote_theme: "pages-themes/dinky@v0.2.0"
theme: minima
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
